parser: "@typescript-eslint/parser"
extends:
 - "plugin:@typescript-eslint/recommended"
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
  files: "src/**/*.ts"
  excludedFiles: "node_modules/**/*"
