printWidth: 100
trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: false
quoteProps: "consistent"
jsxSingleQuote: false
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: "always"
parser: "typescript"
endOfLine: "lf"
noUseBeforeDefine: false
