"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./Chain"));
__export(require("./Either"));
__export(require("./Maybe"));
__export(require("./add"));
__export(require("./adjust"));
var all_1 = require("./all");
exports.all = all_1.all;
exports.every = all_1.all;
__export(require("./allPass"));
__export(require("./and"));
__export(require("./aperture"));
__export(require("./append"));
__export(require("./apply"));
__export(require("./applyTo"));
__export(require("./ascend"));
__export(require("./assoc"));
__export(require("./assocIn"));
__export(require("./both"));
__export(require("./clamp"));
__export(require("./comparator"));
__export(require("./complement"));
__export(require("./compose"));
__export(require("./concat"));
__export(require("./cond"));
var constantly_1 = require("./constantly");
exports.constantly = constantly_1.constantly;
exports.always = constantly_1.constantly;
__export(require("./converge"));
var count_1 = require("./count");
exports.count = count_1.count;
exports.size = count_1.count;
__export(require("./countBy"));
__export(require("./descend"));
__export(require("./dissoc"));
__export(require("./dissocIn"));
var dissocIn_1 = require("./dissocIn");
exports.dissocPath = dissocIn_1.dissocIn;
__export(require("./divide"));
__export(require("./drop"));
__export(require("./dropRepeats"));
__export(require("./dropRepeatsWith"));
__export(require("./dropRight"));
__export(require("./dropRightWhile"));
__export(require("./dropWhile"));
__export(require("./eitherOr"));
__export(require("./empty"));
__export(require("./endsWith"));
var eq_1 = require("./eq");
exports.eq = eq_1.eq;
exports.eqShallow = eq_1.eq;
__export(require("./eqBy"));
__export(require("./eqProps"));
var equals_1 = require("./equals");
exports.eqDeep = equals_1.equals;
exports.equals = equals_1.equals;
__export(require("./F"));
__export(require("./filter"));
__export(require("./filterKeys"));
__export(require("./find"));
__export(require("./findIndex"));
__export(require("./findLast"));
__export(require("./findLastIndex"));
var first_1 = require("./first");
exports.first = first_1.first;
exports.head = first_1.first;
__export(require("./flatMap"));
__export(require("./flatten"));
__export(require("./flow"));
__export(require("./forEach"));
__export(require("./fromPairs"));
__export(require("./get"));
__export(require("./getIn"));
var getOr_1 = require("./getOr");
exports.getOr = getOr_1.getOr;
exports.propOr = getOr_1.getOr;
__export(require("./getValue"));
var getValueOr_1 = require("./getValueOr");
exports.defaultTo = getValueOr_1.getValueOr;
exports.getValueOr = getValueOr_1.getValueOr;
__export(require("./groupBy"));
__export(require("./groupWith"));
__export(require("./gt"));
__export(require("./gte"));
__export(require("./has"));
__export(require("./hasIn"));
__export(require("./identical"));
__export(require("./identity"));
__export(require("./ifElse"));
var includes_1 = require("./includes");
exports.contains = includes_1.includes;
exports.includes = includes_1.includes;
__export(require("./indexBy"));
__export(require("./indexOf"));
var init_1 = require("./init");
exports.butLast = init_1.init;
exports.init = init_1.init;
__export(require("./innerJoin"));
__export(require("./insert"));
__export(require("./insertAll"));
__export(require("./intersection"));
__export(require("./intersperse"));
__export(require("./into"));
__export(require("./invert"));
__export(require("./invertObj"));
// export * from "./invoke";
__export(require("./isEmpty"));
__export(require("./isIn"));
__export(require("./isMonad"));
__export(require("./isNil"));
__export(require("./isNeg"));
__export(require("./isNumber"));
__export(require("./isPos"));
__export(require("./isSome"));
__export(require("./isZero"));
__export(require("./join"));
__export(require("./juxt"));
__export(require("./keys"));
__export(require("./last"));
__export(require("./lt"));
__export(require("./lte"));
__export(require("./map"));
__export(require("./mapIndexed"));
__export(require("./mapKeys"));
__export(require("./mapP"));
__export(require("./match"));
__export(require("./max"));
__export(require("./mean"));
__export(require("./median"));
__export(require("./memoizeWith"));
__export(require("./min"));
__export(require("./mod"));
__export(require("./multiply"));
__export(require("./negate"));
__export(require("./none"));
__export(require("./nonePass"));
__export(require("./not"));
__export(require("./nth"));
__export(require("./of"));
__export(require("./omit"));
__export(require("./partial"));
__export(require("./partition"));
__export(require("./pick"));
__export(require("./pickBy"));
__export(require("./pipe"));
__export(require("./prepend"));
__export(require("./product"));
__export(require("./project"));
__export(require("./prop"));
__export(require("./props"));
__export(require("./propEq"));
__export(require("./propSatisfies"));
__export(require("./range"));
__export(require("./reduce"));
__export(require("./reduceKV"));
__export(require("./reject"));
__export(require("./repeat"));
__export(require("./replace"));
__export(require("./reverse"));
__export(require("./scan"));
__export(require("./sequentialize"));
__export(require("./some"));
__export(require("./somePass"));
__export(require("./sort"));
__export(require("./sortBy"));
__export(require("./split"));
__export(require("./splitAt"));
__export(require("./splitEvery"));
__export(require("./splitWhen"));
__export(require("./spy"));
__export(require("./subtract"));
__export(require("./sum"));
var symmetricDifference_1 = require("./symmetricDifference");
exports.symmetricDifference = symmetricDifference_1.symmetricDifference;
exports.symDiff = symmetricDifference_1.symmetricDifference;
__export(require("./T"));
__export(require("./take"));
__export(require("./takeWhile"));
__export(require("./takeRight"));
__export(require("./takeRightWhile"));
__export(require("./tap"));
__export(require("./test"));
__export(require("./times"));
__export(require("./toLower"));
__export(require("./toPairs"));
__export(require("./toString"));
__export(require("./toUpper"));
__export(require("./trim"));
__export(require("./tryCatch"));
__export(require("./types"));
__export(require("./union"));
__export(require("./unionBy"));
__export(require("./uniq"));
__export(require("./uniqBy"));
__export(require("./unless"));
__export(require("./update"));
__export(require("./updateIn"));
__export(require("./values"));
__export(require("./when"));
__export(require("./where"));
__export(require("./whereEq"));
__export(require("./xor"));
__export(require("./xprod"));
__export(require("./zip"));
__export(require("./zipMap"));
__export(require("./lenses"));
