import { Predicate } from "./types";
export declare const isNil: Predicate<unknown>;
export declare const isFunction: Predicate<unknown>;
export declare const isString: Predicate<unknown>;
export declare const isArray: Predicate<unknown>;
export declare const isNumber: Predicate<unknown>;
export declare const isObject: Predicate<unknown>;
export declare const isEmpty: Predicate<Array<unknown> | Object | string>;
export declare const isNotEmpty: Predicate<Array<unknown> | Object | string>;
export declare const isJust: Predicate<unknown>;
export declare const isNothing: Predicate<unknown>;
export declare const isMaybe: Predicate<unknown>;
export declare const isRight: Predicate<unknown>;
export declare const isLeft: Predicate<unknown>;
export declare const isEither: Predicate<unknown>;
export declare const isMonad: Predicate<unknown>;
export declare const isSome: Predicate<unknown>;
